// <auto-generated />
namespace ReceiptScanner.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ReceiptChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReceiptChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201404301950310_ReceiptChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
